version: "3.9"
services:
  tcpp-db:
    image: mariadb
    # container_name: tcpp-db
    restart: always
    volumes:
      - tcpp-db:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_USER=trinity
      - MYSQL_PASSWORD=trinity
      - MYSQL_ROOT_PASSWORD=trinity
    ports:
      - "127.0.0.1:3308:3306"

  tcpp-base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: dockerize-tcpp/tcpp-base
    # We just need to have this built not running
    scale: 0 
    # volumes:
    #   - ./tcpp-repo:/tcpp-repo

  tcpp-bnetserver:
    build: ./docker/bnetserver
    image: dockerize-tcpp/tcpp-bnetserver
    restart: on-failure
    depends_on:
      - tcpp-base
      - tcpp-db
    ports:
      - '1118'
      - '1119:1119'
    volumes:
      # - ./tcpp-repo:/tcpp-repo
      - ./configs:/tcpp-configs
    # stdin_open: true
    tty: true

  tcpp-worldserver:
    build: ./docker/worldserver
    image: dockerize-tcpp/tcpp-worldserver
    restart: on-failure
    depends_on:
      - tcpp-base
      - tcpp-db
    ports:
        # - '1118:1118' # This one is for the authserver and ony has to open internally
        - '8085:8085'
        - '8086:8086' # this one is also probably not required since it is used for Metrics if enabled (although not sure)
    volumes:
      # - ./tcpp-repo:/tcpp-repo
      - ./server-data:/tcpp-server/data
      - ./configs:/tcpp-configs
      # - tcpp-configs:/tcpp-server/etc
    # https://github.com/moby/moby/issues/2838
    stdin_open: true # this should probably be commented out, since if this is on, when you are attached to the docker container ctr-c will kill the process inside the container instead of detach
    tty: true

volumes:
  tcpp-db:
  # # The only solution that works when trying to get files out (and keep in sync) of the container upon initialisation of the container
  # # https://stackoverflow.com/a/52167722/13620003
  # # However it has to be noted that the ./configs folder NEEDS to exist for this to wokr
  # tcpp-configs:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./configs
