version: "3.9"
services:
  tcpp-db:
    image: mariadb
    # container_name: tcpp-db
    restart: always
    volumes:
      - tcpp-db:/var/lib/mysql
    environment:
      - MYSQL_USER=trinity
      - MYSQL_PASSWORD=trinity
      - MYSQL_ROOT_PASSWORD=trinity
    ports:
      # TODO: make this port only accessible from localhost since it should be just used for debugging the database and not be accessable to non host's on the host's lan
      - "127.0.0.1:3307:3306"

  tcpp-base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: dockerize-tcpp/tcpp-base
    # We just need to have this built not running
    scale: 0 
    # volumes:
    #   - ./tcpp-repo:/tcpp-repo

  tcpp-worldserver:
    build: ./docker/worldserver
    image: dockerize-tcpp/tcpp-worldserver
    depends_on:
      - tcpp-base
      - tcpp-db
    ports:
        # - '1118:1118' # This one is for the authserver and ony has to open internally
        - '8085:8085'
        # - '8086:8086' # this one is also probably not required since it is used for Metrics if enabled (although not sure)
    volumes:
      - ./tcpp-repo:/tcpp-repo
      - ./server-data:/tcpp-server/data
    #   # - ./test:/tcpp-server

volumes:
  tcpp-db:
