version: "3.9"
services:
  tcpp-db:
    image: mariadb
    # container_name: tcpp-db
    restart: always
    volumes:
      - tcpp-db:/var/lib/mysql
    environment:
      - MYSQL_USER=trinity
      - MYSQL_PASSWORD=trinity
      - MYSQL_ROOT_PASSWORD=trinity
    ports:
      # TODO: make this port only accessible from localhost since it should be just used for debugging the database and not be accessable to non host's on the host's lan
      - "3307:3306"

  tcpp-base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: dockerize-tcpp/tcpp-base
    # We just need to have this built not running
    scale: 0 
    # volumes:
    #   - ./tcpp-repo:/tcpp-repo

  tcpp-worldserver:
    build: ./docker/worldserver
    image: dockerize-tcpp/tcpp-worldserver
    depends_on:
      - tcpp-base
      - tcpp-db
    # volumes:
    #   - ./tcpp-repo:/tcpp-repo
    #   # - ./test:/server

volumes:
  tcpp-db:
